### ISSUE TITLE
Nodemon not restarting in docker

### ISSUE THREAD

**Issue by leifdejong** [remy/nodemon#1447]
- `nodemon -v`: 1.18.6 (latest)
- `node -v`: 10.13
- Operating system/terminal environment: 
  - Docker version 18.06.1-ce, build e68fc7a
  - docker-compose version 1.22.0, build f46880f
- Command you ran: 

`docker-compose.yml`:
```yml
version: '3.1'

services:
  node:
    image: node:10
    working_dir: /usr/local/src/
    volumes:
      - .:/usr/local/src/
    environment:
      - NODE_ENV=development
    command: bash -c "nodemon --watch src --exec 'node src/server.js'"
```

Run: `docker-compose up`

### Expected behaviour
Should restart when I change a file in `src/`

### Actual behaviour
Does not restart

### Steps to reproduce
1. `mkdir -p test/src && touch test/docker-compose.yml && touch test/src/server.js`
2. Copy above contents into `docker-compose.yml`
3. Run `cd test && docker-compose up`
4. Try changing something in `server.js` and observe

### Known Solution
If I add the `-L` flag, everything works great! Something got killed in the latest version (https://github.com/docker/labs/issues/378)
