### ISSUE TITLE
Configuration file works outside docker but not inside

### ISSUE THREAD

**Issue by marcospgp** [remy/nodemon#1553]
- `nodemon -v`: (same inside and outside docker) "nodemon": "^1.18.11"
- `node -v`: outside docker: 8.9.4 inside: 10.15
- Operating system/terminal environment: Windows powershell
- Using Docker? What image: yes, node:10.15-alpine

### Expected behaviour

I would expect nodemon to pick up on the nodemon.json configuration file both inside and outside of Docker. I entered a shell in the docker container to make sure the nodemon.json file is there when my app is run with docker.

Outside docker, both the command:

`nodemon --legacy-watch --inspect \"0.0.0.0:9222\" --nolazy --ext \"js,graphql,gql\" dist/bin/www` (without nodemon.json)

and the command:

`nodemon dist/bin/www`

with nodemon.json:

```
{
  "legacy-watch": true,
  "inspect": "0.0.0.0:9222",
  "nolazy": true,
  "watch": ["./dist"],
  "ext": "js,graphql,gql"
}
```

work as expected. The latter however, does not restart the server inside docker when files are changed.

### Actual behaviour

When running inside docker, only passing parameters through the command works. The nodemon.json file doesn't seem to be picked up.

Could it be that there is a problem with passing the legacy watch parameter through the nodemon.json configuration file?

### Steps to reproduce

If you can't reproduce using the command & configuration above, then I can take some time to isolate this bug in my project and try to reproduce it in an isolated repo.

---

If applicable, please append the `--dump` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**.

**Comment by marcospgp** [comment]
Dockerfile:

```
FROM node:10.15-alpine

# Set app directory
WORKDIR /usr/src/app

# Install git in order to allow installing npm packages from Github
RUN set -xe \
    && apk add --no-cache git

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json
# are copied where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ENV NODE_ENV development

EXPOSE 3000

CMD ["npm","start"]
```

Docker compose file:

```
version: "3"
services:
  web:
    build: .
    ports:
      - 3000:3000 # Application port
      - 9222:9222 # Debugging port
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      # More info on the node_modules volume at:
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      # under "The node_modules Volume Trick"
      - /usr/src/app/node_modules
    command: npm run debug
```
