### ISSUE TITLE
nodemon/bin/nodemon.js: not found, running from docker on Win 10

### ISSUE THREAD

**Issue by pedrogzl** [remy/nodemon#1789]
I am new to all technologies used in the project that I am supposed to continue in for my school work. I have confirmed that this bug **does not**  occur on **macOS** but does in **Win10**.
I run **docker-compose up --build** from windows commandline located in directory with index.js, docker files, node_modules,etc.
I am failing to run node.js server with this error:
```
> server@1.0.0 start /usr/src/server
backend | > nodemon index.js
backend |
backend | /usr/src/server/node_modules/.bin/nodemon: 1: /usr/src/server/node_modules/.bin/nodemon: ../nodemon/bin/nodemon.js: not found
backend | npm ERR! file sh
backend | npm ERR! code ELIFECYCLE
backend | npm ERR! errno ENOENT
backend | npm ERR! syscall spawn
backend | npm ERR! server@1.0.0 start: `nodemon index.js `
backend | npm ERR! spawn ENOENT
backend | npm ERR!
backend | npm ERR! Failed at the server@1.0.0 start script.
backend | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
backend |
backend | npm ERR! A complete log of this run can be found in:
backend | npm ERR!     /root/.npm/_logs/2020-10-11T13_03_10_909Z-debug.log
```

**What I tried:**

- added - /usr/src/server/node_modules to volumes
- changed different versions of nodemon in package.json (originally 1.19.4, then I tried 1.17.x and 2.0.3)
- preinstalling nodemon package.json
- ran "start": "nodemon ./index.js " or nodemon with full path
- putting RUN npm install --save nodemon_ in Dockerfile results in _npm ERR! File exists: /usr/src/server/node_modules/.bin/nodemon_
- printenv prints: npm_package_dependencies_nodemon=^1.19.4
- always pruning docker images and starting new
- i cannot access the npm log created, because the docker image was not created since it failed. i cannot see further log details.

This whole project that another person worked on was tested running and working on macOS, and the same person confirmed for me he could not run nodemon on a different windows pc and that he was getting the same error.
Im running Win 10 Enterprise.

**package.json**
```
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon index.js "
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "jsonwebtoken": "^8.5.1",
    "knex": "^0.20.2",
    "knex-list-db-table": "^0.2.0",
    "morgan": "^1.9.1",
    "multer": "^1.4.2",
    "nodemon": "^1.19.4",
    "path": "^0.12.7",
    "pg": "^7.12.1",
    "redis": "^2.8.0",
    "uuid": "^3.3.3"
  }
}
```
**Dockerfile**

```
FROM node:8.11.3

WORKDIR /usr/src/server

COPY ./ ./

RUN npm install

EXPOSE 80
# CMD ["/bin/bash"]
CMD [ "npm", "start" ]
```

**docker.compose**
```
version: '3.6'

services:
  # Backend API
  knizka-server:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/server
    environment:
      POSTGRES_URI: postgres://test:pswd@postgres:5432/server-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - '80:80'
    volumes:
      - ./:/usr/src/server

  #postgres
  postgres:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: server-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - '5432:5432'

  #redis
  redis:
    image: redis
    ports:
      - '6379:6379'
```
(both postgres and redis image is created sucesfully and working)
