### ISSUE TITLE
ignore path failed

### ISSUE THREAD

**Issue by declandragon** [remy/nodemon#2240]
### env

* win 10  22H2 19045.3086
* Docker Desktop 4.36.0 (175267) is currently the newest version available.
* docker-compose.yml
```
version: '3'
services:
  strapi_mysql_3307:
    container_name: strapi_mysql_3307
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  strapi_node_18:
    container_name: strapi_node_18
    image: node:18
    ports:
      - "3001:3000"
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "npm install -g nodemon && npm i && nodemon --exec 'strapi develop'"

```
*  nodemon.json
```
{
  "watch": ["src"],
  "ext": "js,ts,json",
  "ignore": [
    ".git",
    "local/",
    "node_modules/"
  ]
}

```
* node 、npm 、nodemon

![image](https://github.com/user-attachments/assets/ccc5c187-274e-4c60-bdf3-2553e9c0275d)

* package.json
```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "nodemon --watch ./ strapi develop",
    "dev": "nodemon --watch ./ strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "deploy": "strapi deploy"
  },
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.1.0",
    "@notum-cz/strapi-plugin-record-locking": "^1.3.10",
    "@strapi/plugin-cloud": "4.25.13",
    "@strapi/plugin-color-picker": "^4.20.1",
    "@strapi/plugin-i18n": "4.25.13",
    "@strapi/plugin-seo": "^1.9.8",
    "@strapi/plugin-users-permissions": "4.25.13",
    "@strapi/provider-email-mailgun": "^4.25.17",
    "@strapi/provider-upload-aws-s3": "^4.16.2",
    "@strapi/strapi": "4.25.13",
    "@webbio/strapi-plugin-scheduler": "^1.0.6",
    "mysql": "2.18.1",
    "mysql2": "^3.11.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "strapi-content-type-explorer": "^0.2.2",
    "strapi-plugin-preview-button": "^2.2.1",
    "strapi-plugin-soft-delete": "^0.9.6",
    "strapi-plugin-translate": "^1.2.4",
    "strapi-provider-cloudflare-r2": "^0.2.5",
    "strapi-provider-translate-deepl": "^1.1.12",
    "strapi-provider-upload-cloudflare": "./src/extensions/strapi-provider-upload-cloudflare/",
    "styled-components": "5.3.3"
  },
  "devDependencies": {
    "nodemon": "3"
  },
  "workspaces": [
    "./src/plugins/strapi-plugin-ckeditor-custom"
  ],
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "xxxxxx"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  }
}

```

* project file
![image](https://github.com/user-attachments/assets/e4883d62-7470-4347-ba31-7a817c805f9f)

### Expected behaviour

Only monitor the `src` directory

### Actual behaviour

Monitored ignored `local` directory

### Steps to reproduce

run the  docker-compose.yml ，monitoring changes in MySQL files resulted in project restart

![image](https://github.com/user-attachments/assets/996458f9-e954-4662-9c89-f09f85f6fb1c)

![image](https://github.com/user-attachments/assets/0abcee8b-8ec7-4f18-9e1a-ea1211f4a119)
