### ISSUE TITLE
Docker not recognizing file changes

### ISSUE THREAD

**Issue by AndrewBell** [remy/nodemon#866]
Hi all, new to the node community, and love it so far!

I'm struggling to get nodemon to work inside a local development container. I'm running the Windows for Docker (1.12) and using docker-compose. I've set `legacyWatch: true` and tried syncing my clocks (although, I'm not sure what timezone the Hyper-V operates in, I've tried with and without the adjustment). I do use the docker-compose.yml to add the volumes and dev commands necessary for the watch to work (in theory).

I've also tried adding `RUN npm install -g nodemon` in the Dockerfile and changing my docker-compose to `command: ["nodemon", "-L", "--debug", "./app.js", "3000"]` to eliminate a possibility of it being a gulp issue, but no luck.

I appreciate anything help in troubleshooting this issue. Running the gulp task directly seems to work fine.

Steps to reproduce:

1. $ git clone -b docker_reload https://github.com/AndrewBell/wet-tech.git
2. $ docker-compose build
3. $ docker-compose up
4. Edit app.js

Here are the files in question:

**gulpfile.js**
```
var gulp = require('gulp');
var nodemon = require('gulp-nodemon');

var watch = require('gulp-watch');
server = require( 'gulp-develop-server' );

gulp.task('dev-legacy', function () {
    nodemon({
        script: 'app.js',
        ext: 'js',
        legacyWatch: true
    })
});

```

**Dockerfile**
```
FROM node:argon

# Configure Timezone (needed for nodemon)
RUN echo "America/Chicago" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

# Create app directories
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app
RUN npm install gulp -g
RUN npm install

# Bundle app source
COPY app.js /usr/src/app
COPY gulpfile.js /usr/src/app

EXPOSE 3000

CMD ["npm", "start"]
```

**docker-compose.yml**
```
version: '2'
services:
  pending-service:
    build: ./pending-service
    image: recursivechaos/pending-service
    ports:
      - "3000:3000"
    volumes:
      # The following is a hack for Windows host machines, Mac users may exclude the leading //
      - //./pending-service:/usr/src/app
    command: [gulp, dev-legacy]
```
